# Generated by Django 4.0.5 on 2022-06-02 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de la categoria')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre de la categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del estado')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre del estado')),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de tipo usuario')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre del tipo usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='id del usuario')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre del usuario')),
                ('apellido', models.CharField(max_length=20, verbose_name='Apellido del usuario')),
                ('correo', models.CharField(max_length=30, verbose_name='Mail del usuario')),
                ('clave', models.CharField(max_length=20, verbose_name='Clave del usuario')),
                ('foto', models.ImageField(null=True, upload_to='')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.estado')),
                ('tipousuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='Tabla',
            fields=[
                ('id_tema', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del tema')),
                ('nom_dato', models.CharField(max_length=50, verbose_name='nombre del enemigo')),
                ('foto', models.ImageField(null=True, upload_to='')),
                ('tipodato', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=250, verbose_name='contenido del comentario del foro')),
                ('f_creacion', models.DateTimeField(verbose_name='fecha de creacion')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.categoria')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.estado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id_mensaje', models.AutoField(primary_key=True, serialize=False, verbose_name='Mensaje que se le envia al usuario')),
                ('titulo', models.CharField(max_length=30, verbose_name='titulo del mensaje')),
                ('f_creacion', models.DateTimeField(verbose_name='Fecha de la creacion')),
                ('contenido', models.CharField(max_length=250, verbose_name='contenido del mensaje')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.estado')),
                ('tipousuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.tipousuario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del comentario')),
                ('titulo_com', models.CharField(max_length=50, verbose_name='Titulo del comentario')),
                ('f_creacion', models.DateTimeField(verbose_name='fecha de la creacion')),
                ('texto', models.CharField(max_length=250, verbose_name='descripcion del comentario')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.estado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.usuario')),
            ],
        ),
    ]
