# Generated by Django 4.0.4 on 2022-06-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='f_creacion',
            field=models.DateTimeField(blank=True, verbose_name='fecha de la creacion'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=models.CharField(blank=True, max_length=250, verbose_name='descripcion del comentario'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='titulo_com',
            field=models.CharField(blank=True, max_length=50, verbose_name='Titulo del comentario'),
        ),
    ]
